export const TAGS = [
    'AI',
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    'Natural Language Processing',
    'Angular',
    'Standalone Components',
    'Angular Compiler',
    'Ivy',
    'Signals',
    'Signal Forms',
    'httpResource',
    'Resource API',
    'Hybrid Rendering',
    'SSR',
    'Server-Side Rendering',
    'SSG',
    'Prerendering',
    'Deferrable Views',
    'Event Replay',
    'Incremental Hydration',
    'Routing',
    'Route-specific Providers',
    'Angular Material',
    'Angular Material Styling API',
    'Micro-Frontends',
    'NgRx',
    'NgRx SignalStore',
    'Entity Management',
    'Flux Architecture',
    'Linked State',
    'Global State',
    'Signal-based State',
    'Performance Optimization',
    'Performance Monitoring',
    'Code Health',
    'Forensic Code Analysis',
    'Hotspots',
    'Change Coupling',
    'Architecture Validation',
    'ESLint Architecture Rules',
    'Sheriff',
    'Refactoring',
    'Migration',
    'Component Testing',
    'Playwright',
    'E2E Testing',
    'Cypress',
    'Test Debugging',
    'Mocking',
    'TDD',
    'AI-Assisted TDD',
    'Web APIs',
    'HTML/CSS Components',
    'requestIdleCallback',
    'Browser Event Loop',
    'INP',
    'Web Performance Metrics',
    'Accessibility',
    'Native Web Components',
    'WebStorm',
    'Angular CLI',
    'TypeScript',
    'TypeScript API Clients',
    'Transformers.js',
    'HTMX',
    'Postman',
    'Newman',
    'Johnny-Five',
    'Espruino',
    'Node.js',
    'Mapbox MCP',
    'MCP DevKit',
    'Large Language Models',
    'LLMs',
    'Transformers',
    'Embeddings',
    'Tokenizers',
    'Agentic AI',
    'AI Agents',
    'Multi-Agent Systems',
    'RAG',
    'Vector Databases',
    'Weaviate',
    'On-Device AI',
    'WebLLM',
    'TensorFlow.js',
    'MediaPipe',
    'PEFT',
    'LoRA',
    'QLoRA',
    'Quantization',
    'Edge Inference',
    'Context Engineering',
    'Conversational Decision Support',
    'Forecasting Models',
    'Time-Series Prediction',
    'Model Optimization',
    'OAuth 2.0',
    'XSS',
    'Refresh Token Rotation',
    'Backend-for-Frontend',
    'BFF',
    'API Security',
    'RxJS',
    'Observables',
    'Marko.js',
    'Nuxt',
    'Vue',
    'React',
    'JavaScript',
    'JavaScript Performance',
    'IoT',
    'Embedded Programming',
    'Arduino',
    'ESP32',
    'Raspberry Pi',
    'API Lifecycle',
    'API Testing Pipelines',
    'Queue Patterns',
    'Database Patterns',
    'Google',
];

export const countryFlags = {
  "USA": { 
    emoji: "🇺🇸", 
    code: "US",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg"
  },
  "Germany": { 
    emoji: "🇩🇪", 
    code: "DE",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg"
  },
  "France": { 
    emoji: "🇫🇷", 
    code: "FR",
    flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg"
  }, 
  "Colombia": { 
    emoji: "🇨🇴", 
    code: "CO",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg"
  },
  "Poland": { 
    emoji: "🇵🇱", 
    code: "PL",
    flag: "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg"
  },
  "Austria": { 
    emoji: "🇦🇹", 
    code: "AT",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg"
  },
  "Canada": { 
    emoji: "🇨🇦", 
    code: "CA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg"
  },
  "Israel": { 
    emoji: "🇮🇱", 
    code: "IL",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"
  },
  "Czech Republic": { 
    emoji: "🇨🇿", 
    code: "CZ",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg"
  },
  "Switzerland": { 
    emoji: "🇨🇭", 
    code: "CH",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg"
  }
};